language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - ${HOME}/.composer/cache

install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - vendor/bin/phpunit

notifications:
  slack:
    secure: JAx7wvdrR7nM7stk7YrWos65JbTFxVlNWES8eNt2EVxcYdYUK57UnVHmXNjA3qgurBjEFWE2LlKvoAydsKeZUg3NjmcqJY2keag/mUdJcQTJZ/olFFaMf3p+qNN/4KnyDQ3NqNWT7ioId/cIdHVbndkB14WGtZWH7k9xmLVt2S8AQd+DWjzwQhzqhTAeSBqZq/bZ+7srM9uZFkYLBNtYfNwGJNs1EhTPMYL0EaGLK58k/PBQru5U9ruipKsMy9jDTiXEss5aJGkwvy5oa6MjoPstPXIqwJpk3zrXyicvJTC55Ztzwypj2irkcW/jhPhuxRtXk10X8XW55aznEJL0e9vJJt/FrC3Inv4QXu+XntMNP5QBdLxQZbRuquRY8msESw2niUuJEZAo6KWwnrSIOkCwCkWah6PYGoC3JuBU2JV3KBV/47pn9EJlz1DWkV+DSF0Hmskgjep90hSU9F4OFGunBlNBwdNwihu6Kfg524dQpINwPavVoAuVflJyP2hrQIqDjvxZ+qemlpJBG8htwB4cX4ZBBU2jVVFQ+T1kY0OclL2dSElek8wTT0eoOkEOfjMQFgkB6VWxmq7hz5bRxbV3iAvhzRTyzSMgqpQES7V3fRhJwtHL9+K0R6NjIqxLXyTnxIQD12kF7ZHbRAsQDiWbNzJa8ea8u88Y3OzWeGk=
